os: osx
osx_image: xcode10.2
language: ruby
dist: bionic
#rvm:
#  - 2.6.5
branches:
  only:
    - master
deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file: emacs.tar.gz
  skip_cleanup: true
